### PR TITLE
add autofocus to search input control

### PR DESCRIPTION
**Pull request by inoas**
I did not test this, I just skimmed through the code on github after seeing that it does not grab focus on entering the page.

### CODE REVIEW

**Comment by ghivert** [comment]
Do you have an opinion on [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus#accessibility_concerns)? I'm concerned about accessibility. I know I'm not the best on this and I'd really like to make Gloogle as much accessible as possible to make sure everyone can use it. 🙂

**Comment by adelhult** [comment]
Were also just about to contribute with this change before I found this PR :sweat_smile: .

I don’t have much to add about the accessibility concerns, but as a reference: [crates](https://crates.io/) and [hoogle](https://hoogle.haskell.org/) uses the autofocus attribute and [npm](https://www.npmjs.com/) does not. 

(Awesome work on the website btw @ghivert, it's really nice!).

**Comment by inoas** [comment]
at least it is quick now by pressing s.

**Comment by ghivert** [comment]
Let's try, and see if someone is bothered or not.

**Review by ghivert — APPROVED** [review]

**Pull request merged**
